# this file uses prebuilt image in dockerhub
services:
  jekyll:
    # Switch to building from local Dockerfile instead of using prebuilt image
    build: .  # build context is the project root
    container_name: al-folio-website
    command: bash -c "
      bundle install --jobs 4 --retry 3
      && rm -f Gemfile.lock
      && bundle exec jekyll serve --watch --port=4000 --host=0.0.0.0 --livereload --verbose"
    ports:
      - 4000:4000  # map host port 4000 to container port 4000
    volumes:
      - .:/srv/jekyll
      - bundle:/srv/jekyll/vendor/bundle

# Define named volumes
volumes:
  bundle: {}
